spring:
  h2:
    console:
      enabled: true
  datasource:
    generate-unique-name: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate
    defer-datasource-initialization: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
